In [ ]:
import pandas as pd

df_dim_product = pd.read_parquet('../../data/gold/data_warehouse/dw_dim_product.parquet')
df_dim_region = pd.read_parquet('../../data/gold/data_warehouse/dw_dim_region.parquet')
df_dim_supplier = pd.read_parquet('../../data/gold/data_warehouse/dw_dim_supplier.parquet')
df_dim_time_series = pd.read_parquet('../../data/gold/data_warehouse/dw_dim_time_series.parquet')  
df_dim_weekly_calendar = pd.read_parquet('../../data/gold/data_warehouse/dw_dim_weekly_calendar.parquet')
df_fact_sales_weekly = pd.read_parquet('../../data/gold/data_warehouse/dw_fact_sales_weekly.parquet')

#datasets
df_base_dataset = pd.read_parquet('../../data/gold/forecasting/datasets/ds_base_dataset.parquet')
df_ds_erratic_base_time_series = pd.read_parquet('../../data/gold/forecasting/datasets/ds_erratic_base_timeseries.parquet')
df_ds_intermittent_base_time_series = pd.read_parquet('../../data/gold/forecasting/datasets/ds_intermittent_base_timeseries.parquet')
df_ds_lumpy_base_time_series = pd.read_parquet('../../data/gold/forecasting/datasets/ds_lumpy_base_timeseries.parquet')
df_ds_segmented_time_series = pd.read_parquet('../../data/gold/forecasting/datasets/ds_segmented_time_series.parquet')
df_ds_smooth_base_time_series = pd.read_parquet('../../data/gold/forecasting/datasets/ds_smooth_base_timeseries.parquet')

#features
df_time_series_lag_features = pd.read_parquet('../../data/gold/forecasting/features/ds_time_series_lag_features.parquet')
df_time_series_product_features = pd.read_parquet('../../data/gold/forecasting/features/ds_time_series_product_features.parquet')
df_time_series_statistical_features = pd.read_parquet('../../data/gold/forecasting/features/ds_time_series_statistical_features.parquet')
df_time_series_time_features = pd.read_parquet('../../data/gold/forecasting/features/ds_time_series_time_features.parquet')

#tags
df_time_series_outliers_detected = pd.read_parquet('../../data/gold/forecasting/tags/ds_time_series_outliers_detected.parquet')
df_time_series_segmented_classified = pd.read_parquet('../../data/gold/forecasting/tags/ds_time_series_segmented_classified.parquet')
df_time_series_outliers_detected = pd.read_parquet('../../data/gold/forecasting/tags/ds_time_series_outliers_detected.parquet')

In [5]:
df_dim_product.head(5)

,product_id,product_attribute_1,product_attribute_2,product_attribute_3,product_name
0,1,B,C,B24,Product 1
1,2,B,C,B16,Product 2
2,3,A,A,A08,Product 3
3,4,B,C,B24,Product 4
4,5,B,C,B32,Product 5

In [6]:
df_dim_region.head(5)

   region_id   region_name
0          1  Centro-Oeste
1          2      Nordeste
2          3         Norte
3          4       Sudeste
4          5           Sul

In [7]:
df_dim_supplier.head(5)

   supplier_id supplier_name
0            1    Supplier 1
1            2    Supplier 2
2            3    Supplier 3
3            4    Supplier 4
4            5    Supplier 5

In [8]:
df_dim_time_series.head(5)

,time_series_id,supplier_id,region_id,product_id,first_week_date,last_week_date,total_weeks_length,num_week_with_sales,num_week_with_zeros,sales_units,...,std_weekly_sales,std_weekly_sales_non_zero,max_weekly_sales,min_weekly_sales,q25_sales,q50_sales,q75_sales,sales_weeks_ratio,cv,iqr
0,1,1,5,69,2023-01-09,2023-08-21,33,4,29,10.0,...,1.103541,2.380476,6.0,0.0,0.00,0.0,0.00,0.121212,3.641674,0.0
1,2,1,5,89,2023-03-06,2024-10-21,86,33,53,1716.0,...,65.791275,98.889142,375.0,0.0,0.00,0.0,6.00,0.383721,3.297232,6.0
2,3,1,5,97,2022-10-31,2023-01-30,14,3,11,5.0,...,0.744946,0.577350,2.0,0.0,0.00,0.0,0.00,0.214286,2.085844,0.0
3,4,1,5,121,2022-10-31,2024-10-21,104,83,21,9966.0,...,90.341149,85.469119,393.0,0.0,17.25,82.0,145.25,0.798077,0.942753,128.0
4,5,1,5,134,2022-10-31,2024-10-21,104,48,56,14208.0,...,670.247126,967.627918,5646.0,0.0,0.00,0.0,39.00,0.461538,4.906088,39.0

In [9]:
df_dim_weekly_calendar.head(5)

,week_date,week,start_date,end_date,year,semester,semester_date,semester_name,quarter,quarter_date,quarter_name,month,month_name,month_date
0,2022-10-31,44,2022-10-31,2022-11-06,2022,2,2022-10-01,H2,4,2022-10-01,Q4,10,October,2022-10-01
1,2022-11-07,45,2022-11-07,2022-11-13,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01
2,2022-11-14,46,2022-11-14,2022-11-20,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01
3,2022-11-21,47,2022-11-21,2022-11-27,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01
4,2022-11-28,48,2022-11-28,2022-12-04,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01

In [10]:
df_fact_sales_weekly.head(5)

   week_date  supplier_id  region_id  product_id  time_series_id  units_sold
0 2022-10-31            1          5          97               3           2
1 2022-10-31            1          5         121               4          61
2 2022-10-31            1          5         134               5         189
3 2022-10-31            1          5         241              12        5064
4 2022-10-31            1          5         246              13          22

In [11]:
df_base_dataset.head(5)

,time_series_id,week_date,supplier_id,region_id,product_id,units_sold,week,start_date,end_date,year,...,q50_sales,q75_sales,iqr,cv,supplier_name,region_name,product_name,product_attribute_1,product_attribute_2,product_attribute_3
0,1,2023-01-09,1,5,69,2,2,2023-01-09,2023-01-15,2023,...,0,0,0.0,3.641674,Supplier 1,Sul,Product 69,A,A,A04
1,1,2023-01-16,1,5,69,6,3,2023-01-16,2023-01-22,2023,...,0,0,0.0,3.641674,Supplier 1,Sul,Product 69,A,A,A04
2,1,2023-01-23,1,5,69,0,4,2023-01-23,2023-01-29,2023,...,0,0,0.0,3.641674,Supplier 1,Sul,Product 69,A,A,A04
3,1,2023-01-30,1,5,69,0,5,2023-01-30,2023-02-05,2023,...,0,0,0.0,3.641674,Supplier 1,Sul,Product 69,A,A,A04
4,1,2023-02-06,1,5,69,0,6,2023-02-06,2023-02-12,2023,...,0,0,0.0,3.641674,Supplier 1,Sul,Product 69,A,A,A04

In [12]:
df_ds_erratic_base_time_series.head(5)

,time_series_id,week_date,supplier_id,region_id,product_id,units_sold,week,start_date,end_date,year,...,q75_sales,iqr,cv,supplier_name,region_name,product_name,product_attribute_1,product_attribute_2,product_attribute_3,demand_type
0,4,2022-10-31,1,5,121,61,44,2022-10-31,2022-11-06,2022,...,145,128.0,0.942753,Supplier 1,Sul,Product 121,C,B,B02,erratic
1,4,2022-11-07,1,5,121,9,45,2022-11-07,2022-11-13,2022,...,145,128.0,0.942753,Supplier 1,Sul,Product 121,C,B,B02,erratic
2,4,2022-11-14,1,5,121,18,46,2022-11-14,2022-11-20,2022,...,145,128.0,0.942753,Supplier 1,Sul,Product 121,C,B,B02,erratic
3,4,2022-11-21,1,5,121,3,47,2022-11-21,2022-11-27,2022,...,145,128.0,0.942753,Supplier 1,Sul,Product 121,C,B,B02,erratic
4,4,2022-11-28,1,5,121,8,48,2022-11-28,2022-12-04,2022,...,145,128.0,0.942753,Supplier 1,Sul,Product 121,C,B,B02,erratic

In [13]:
df_ds_intermittent_base_time_series.head(5)

,time_series_id,week_date,supplier_id,region_id,product_id,units_sold,week,start_date,end_date,year,...,q75_sales,iqr,cv,supplier_name,region_name,product_name,product_attribute_1,product_attribute_2,product_attribute_3,demand_type
0,3,2022-10-31,1,5,97,2,44,2022-10-31,2022-11-06,2022,...,0,0.0,2.085844,Supplier 1,Sul,Product 97,A,A,A03,intermittent
1,3,2022-11-07,1,5,97,0,45,2022-11-07,2022-11-13,2022,...,0,0.0,2.085844,Supplier 1,Sul,Product 97,A,A,A03,intermittent
2,3,2022-11-14,1,5,97,0,46,2022-11-14,2022-11-20,2022,...,0,0.0,2.085844,Supplier 1,Sul,Product 97,A,A,A03,intermittent
3,3,2022-11-21,1,5,97,0,47,2022-11-21,2022-11-27,2022,...,0,0.0,2.085844,Supplier 1,Sul,Product 97,A,A,A03,intermittent
4,3,2022-11-28,1,5,97,0,48,2022-11-28,2022-12-04,2022,...,0,0.0,2.085844,Supplier 1,Sul,Product 97,A,A,A03,intermittent

In [14]:
df_ds_lumpy_base_time_series.head(5)

,time_series_id,week_date,supplier_id,region_id,product_id,units_sold,week,start_date,end_date,year,...,q75_sales,iqr,cv,supplier_name,region_name,product_name,product_attribute_1,product_attribute_2,product_attribute_3,demand_type
0,1,2023-01-09,1,5,69,2,2,2023-01-09,2023-01-15,2023,...,0,0.0,3.641674,Supplier 1,Sul,Product 69,A,A,A04,lumpy
1,1,2023-01-16,1,5,69,6,3,2023-01-16,2023-01-22,2023,...,0,0.0,3.641674,Supplier 1,Sul,Product 69,A,A,A04,lumpy
2,1,2023-01-23,1,5,69,0,4,2023-01-23,2023-01-29,2023,...,0,0.0,3.641674,Supplier 1,Sul,Product 69,A,A,A04,lumpy
3,1,2023-01-30,1,5,69,0,5,2023-01-30,2023-02-05,2023,...,0,0.0,3.641674,Supplier 1,Sul,Product 69,A,A,A04,lumpy
4,1,2023-02-06,1,5,69,0,6,2023-02-06,2023-02-12,2023,...,0,0.0,3.641674,Supplier 1,Sul,Product 69,A,A,A04,lumpy

In [15]:
df_ds_segmented_time_series.head(5)

   time_series_id       segment
0               1  discontinued
1               2         valid
2               3  discontinued
3               4         valid
4               5         valid

In [16]:
df_ds_smooth_base_time_series.head(5)

,time_series_id,week_date,supplier_id,region_id,product_id,units_sold,week,start_date,end_date,year,...,q75_sales,iqr,cv,supplier_name,region_name,product_name,product_attribute_1,product_attribute_2,product_attribute_3,demand_type
0,9,2023-05-01,1,5,185,18,18,2023-05-01,2023-05-07,2023,...,17,2.0,0.176777,Supplier 1,Sul,Product 185,A,A,A05,smooth
1,9,2023-05-08,1,5,185,14,19,2023-05-08,2023-05-14,2023,...,17,2.0,0.176777,Supplier 1,Sul,Product 185,A,A,A05,smooth
2,15,2022-10-31,1,5,289,4,44,2022-10-31,2022-11-06,2022,...,4,0.0,0.000000,Supplier 1,Sul,Product 289,A,A,A05,smooth
3,16,2024-07-01,1,5,294,3,27,2024-07-01,2024-07-07,2024,...,3,2.0,0.912870,Supplier 1,Sul,Product 294,A,A,A05,smooth
4,16,2024-07-08,1,5,294,1,28,2024-07-08,2024-07-14,2024,...,3,2.0,0.912870,Supplier 1,Sul,Product 294,A,A,A05,smooth

In [17]:
df_time_series_lag_features.head(5)

,time_series_id,week_date,units_sold,lag_4,lag_5,lag_13,lag_14,lag_27,lag_28,lag_52
0,2,2023-03-06,28,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,2,2023-03-13,11,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,2,2023-03-20,24,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,2,2023-03-27,48,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,2,2023-04-03,6,28,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [18]:
df_time_series_product_features.head(5)

   time_series_id product_attribute_1 product_attribute_2 product_attribute_3
0               2                   A                   A                 A01
1               4                   C                   B                 B02
2               5                   C                   B                 B02
3               7                   C                   B                 B02
4              12                   A                   A                 A05

In [19]:
df_time_series_statistical_features.head(5)

,time_series_id,avg_weekly_sales,avg_weekly_sales_non_zero,std_weekly_sales,std_weekly_sales_non_zero,max_weekly_sales,min_weekly_sales,q25_sales,q50_sales,q75_sales,iqr,cv
0,2,19.953489,52.000000,65.791275,98.889142,375,0,0,0,6,6.00,3.297232
1,4,95.826920,120.072289,90.341148,85.469119,393,0,17,82,145,128.00,0.942753
2,5,136.615387,296.000000,670.247131,967.627918,5646,0,0,0,39,39.00,4.906088
3,7,0.520548,1.727273,1.313494,1.931735,10,0,0,0,1,1.00,2.523286
4,12,1657.442261,1758.918367,2018.142334,2035.805029,11981,0,576,969,1842,1265.75,1.217624

In [20]:
df_time_series_time_features.head(5)

   time_series_id  week_date  year  semester  quarter  month  week
0               2 2023-03-06  2023         1        1      3    10
1               2 2023-03-13  2023         1        1      3    11
2               2 2023-03-20  2023         1        1      3    12
3               2 2023-03-27  2023         1        1      3    13
4               2 2023-04-03  2023         1        2      4    14

In [21]:
df_time_series_outliers_detected.head(5)

,week_date,time_series_id,units_sold,segment,is_outlier,rolling_baseline,upper_threshold,lower_threshold,units_sold_original,units_sold_capped,units_sold_removed,units_sold_interpolated
33,2023-03-06,2,28,valid,False,20.0,60.0302,0.0,28.0,28.0,28.0,28.0
34,2023-03-13,2,11,valid,False,20.0,60.0302,0.0,11.0,11.0,11.0,11.0
35,2023-03-20,2,24,valid,False,22.0,82.0453,0.0,24.0,24.0,24.0,24.0
36,2023-03-27,2,48,valid,False,22.0,82.0453,0.0,48.0,48.0,48.0,48.0
37,2023-04-03,2,6,valid,False,22.0,82.0453,0.0,6.0,6.0,6.0,6.0

In [22]:
df_time_series_segmented_classified.head(5)

   time_series_id       segment demand_type sugested_model
0               1  discontinued        None      end_cycle
1               2         valid       lumpy    statistical
2               3  discontinued        None      end_cycle
3               4         valid     erratic    statistical
4               5         valid       lumpy    statistical

In [23]:
df_time_series_outliers_detected.head(5)

,week_date,time_series_id,units_sold,segment,is_outlier,rolling_baseline,upper_threshold,lower_threshold,units_sold_original,units_sold_capped,units_sold_removed,units_sold_interpolated
33,2023-03-06,2,28,valid,False,20.0,60.0302,0.0,28.0,28.0,28.0,28.0
34,2023-03-13,2,11,valid,False,20.0,60.0302,0.0,11.0,11.0,11.0,11.0
35,2023-03-20,2,24,valid,False,22.0,82.0453,0.0,24.0,24.0,24.0,24.0
36,2023-03-27,2,48,valid,False,22.0,82.0453,0.0,48.0,48.0,48.0,48.0
37,2023-04-03,2,6,valid,False,22.0,82.0453,0.0,6.0,6.0,6.0,6.0